[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
; build_flags = -D DEBUG_MODE
lib_deps = xreef/PCF8574 library@^2.3.7
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
